// Source: src/dev/App.civet
// Generated by Civetman

import { Counter } from "../components/Counter"
export const App = () => <Counter />

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiIiwic291cmNlcyI6WyJ1bmtub3duIl0sIm1hcHBpbmdzIjoiQUFBVyxPQUFYLENBQUMsQ0FBQyxPQUFPLENBQUMsQ0FBQyxDQUFDLElBQUksQ0FBQyx1QkFBdUI7QUFDeEMsQUFBQSxBQUFBLE1BQU0sQ0FBSSxNQUFILEdBQUcsQ0FBQyxDQUFFLENBQUMsRSxHQUFFLEMsQyxPQUFTLEMsRUFBRztBQUM1QiIsIm5hbWVzIjpbXSwic291cmNlc0NvbnRlbnQiOlsieyBDb3VudGVyIH0gZnJvbSBcIi4uL2NvbXBvbmVudHMvQ291bnRlclwiXG5leHBvcnQgQXBwIDo9ID0+IDxDb3VudGVyIC8+XG4iXX0=
